version: '3.3'

services:
  minio:
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    container_name: minio
    command: server --console-address :9001 /data
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@127.0.0.1:5432/test
    volumes:
      - s3:/data

  postgres:
    image: postgres:13
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  s3:
  pg:
